### ISSUE TITLE
api playercareerstats returns an unexpected result type causing player_career_stats to error

### ISSUE THREAD

**Issue by wjduenow** [dagrz/nba_stats#1]
Unexpected result types: 
- SeasonRankingsRegularSeason
- SeasonRankingsPostSeason

Error:
result = client.player_career_stats(893)
NbaStats::BadResponseError: Unexpected result set name season_rankings_regular_season.

Example API Call: http://stats.nba.com/stats/playercareerstats?PlayerID=893&PerMode=Totals

**Comment by dagrz** [comment]
Should be fixed now, along with some other similar bugs.
